# Generated by Django 4.0.10 on 2023-03-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_dweet_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='dwitter.dweet'),
        ),
    ]
