# Generated by Django 4.0.10 on 2023-03-17 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0004_dweet_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
